#!/bin/bash

set -x

#COMANDO PARA MOSTRAR EL USO DE CPU Y MEMORIA DE LOS PROCESOS DE UNA SESION
#ps -o pid,pcpu,pmem

memoria_total=0
cpu_total=0
procesos_totales=0
archivos_abiertos_totales=0

#EL FLAG LO UTILIZO PARA NO TENER EN CUENTA LA PRIMER LINEA DEL COMANDO 'ps'
#procesos_totales=`ps -o pid,pcpu,pmem |
#	awk 'BEGIN { procesos =  0 ; flag = 0}
#	{ if(flag > 0) procesos++; flag = 1 }
#	END {print procesos}'`

#FORMA ENCONTRADA EN GOOGLE
#procesos_totales=$(ps -A r | wc -l)

#memoria_total=`ps -o pid,pcpu,pmem |
#	awk 'BEGIN { memoria = 0 ; flag = 0}
#	{ if(flag > 0) memoria+=$3; flag = 1 }
#	END {print memoria}'`
#
#cpu_total=`ps -o pid,pcpu,pmem |
#	awk 'BEGIN { cpu = 0 ; flag = 0}
#	{ if(flag > 0) memoria+=$2; flag = 1 }
#	END {print cpu}'`

archivos_abiertos_totales=`ps -o pid,pcpu,pmem |
	awk 'BEGIN { archivos_abiertos = 0; flag = 0 }
	{ 
		if (flag > 0){
		archivos_abiertos+='find /proc/$1/fd -type l | wc -l'
		}
		flag = 1;
	}
'`

#LA CANTIDAD DE ARCHIVOS SIMBOLICOS DENTRO DE LA RUTA
# find ruta -type l | wc -l

#echo "memoria usada: $memoria_total"
#echo "cpu usada: $cpu_total"
#echo "cantidad de procesos: $procesos_totales"
#echo "archivos abiertos por los procesos: $archivos_abiertos_totales"
